# Generated by Django 5.0.3 on 2024-04-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_category', models.CharField(max_length=100, verbose_name='Категории блюд')),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Средняя стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Ресторана')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес Ресторана')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Номер Ресторана')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('subheading', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('info', models.TextField(verbose_name='Информация')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Uniqueness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Связь с рестораном')),
                ('display_phone', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('display_address', models.BooleanField(default=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Район')),
                ('display_district', models.BooleanField(default=True)),
                ('kitchen_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кухня')),
                ('display_kitchen_type', models.BooleanField(default=True)),
                ('for_child', models.CharField(blank=True, max_length=100, null=True, verbose_name='Для детей')),
                ('display_for_child', models.BooleanField(default=True)),
                ('deposit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Депозит')),
                ('display_deposit', models.BooleanField(default=True)),
                ('delivery', models.CharField(blank=True, max_length=50, null=True, verbose_name='Доставка')),
                ('display_delivery', models.BooleanField(default=True)),
                ('summer_terrace', models.CharField(blank=True, max_length=50, null=True, verbose_name='Летняя терраса')),
                ('display_summer_terrace', models.BooleanField(default=True)),
                ('vip', models.CharField(blank=True, max_length=100, null=True, verbose_name='VIP')),
                ('display_vip', models.BooleanField(default=True)),
                ('live_music', models.CharField(blank=True, max_length=50, null=True, verbose_name='Живая музыка')),
                ('display_live_music', models.BooleanField(default=True)),
                ('own_pastry_shop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Своя кондитерская')),
                ('display_own_pastry_shop', models.BooleanField(default=True)),
                ('cycle_parking', models.CharField(blank=True, max_length=50, null=True, verbose_name='Велопарковка')),
                ('display_cycle_parking', models.BooleanField(default=True)),
                ('parking', models.CharField(blank=True, max_length=50, null=True, verbose_name='Парковка')),
                ('display_parking', models.BooleanField(default=True)),
                ('breakfast', models.CharField(blank=True, max_length=100, null=True, verbose_name='Завтрак')),
                ('display_breakfast', models.BooleanField(default=True)),
                ('business_lunch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бизнес-ланч')),
                ('display_business_lunch', models.BooleanField(default=True)),
                ('show_programmes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Шоу программа')),
                ('display_show_programmes', models.BooleanField(default=True)),
                ('Music', models.CharField(blank=True, max_length=50, null=True, verbose_name='Музыка')),
                ('display_Music', models.BooleanField(default=True)),
                ('Chef', models.CharField(blank=True, max_length=50, null=True, verbose_name='Шев-повар')),
                ('display_Chef', models.BooleanField(default=True)),
                ('hallsVenues', models.CharField(blank=True, max_length=100, null=True, verbose_name='Залы и место')),
                ('display_hallsVenues', models.BooleanField(default=True)),
                ('dance_floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Танцпол')),
                ('display_dance_floor', models.BooleanField(default=True)),
                ('cloakroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гардеробная')),
                ('display_cloakroom', models.BooleanField(default=True)),
                ('restaurant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.restaurant')),
            ],
        ),
    ]
