# Generated by Django 5.0.3 on 2024-04-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAverageCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averagecheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.averagecheck')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'averagecheck')},
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='check_dish',
            field=models.ManyToManyField(through='page.RestaurantAverageCheck', to='page.averagecheck'),
        ),
    ]
