# Generated by Django 5.0.3 on 2024-04-09 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_restaurantaveragecheck_restaurant_check_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=60, unique=True, verbose_name='Почта ресторана'),
            preserve_default=False,
        ),
    ]
