# Generated by Django 5.0.3 on 2024-04-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_newspromotion_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='check_dish',
        ),
        migrations.AddField(
            model_name='averagecheck',
            name='restaurant',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='page.restaurant', verbose_name='Ресторан'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RestaurantAverageCheck',
        ),
    ]
