# Generated by Django 5.0.3 on 2024-04-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_uniqueness_cabins_uniqueness_children_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Категории')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='dish_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название Блюда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='Menu/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.category_menu')),
            ],
        ),
    ]
