# Generated by Django 5.0.3 on 2024-04-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_workinghours_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.restaurant'),
        ),
    ]
