# Generated by Django 5.0.3 on 2024-04-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.restaurant'),
        ),
    ]
