# Generated by Django 5.0.3 on 2024-05-01 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_order_orderdish_order_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время принятие заказа'),
            preserve_default=False,
        ),
    ]
