# Generated by Django 5.0.3 on 2024-05-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_order_order_time'),
        ('rg', '0007_alter_guest_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rg.guest')),
            ],
        ),
        migrations.CreateModel(
            name='CartDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.cart')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.dishmenu')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(through='page.CartDish', to='page.dishmenu'),
        ),
    ]
