# Generated by Django 5.0.3 on 2024-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
