# Generated by Django 5.0.3 on 2024-04-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_restaurantaveragecheck_restaurant_check_dish'),
        ('rg', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='page.restaurant'),
            preserve_default=False,
        ),
    ]
