# Generated by Django 5.0.3 on 2024-04-09 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0003_customer_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='restaurant_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=60, unique=True, verbose_name='Почта ресторана'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='Админ'),
        ),
    ]
