# Generated by Django 5.0.3 on 2024-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0004_customer_restaurant_email_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='restaurant_email',
            field=models.EmailField(max_length=60, verbose_name='Почта ресторана'),
        ),
    ]
