# Generated by Django 5.0.3 on 2024-04-21 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0005_alter_customer_restaurant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Время входа в аккаунт')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания аккаунта')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Адрес электронной почты')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. Всего 11 цифр.", regex='^\\+7\\d{10}$')], verbose_name='Номер телефона')),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='GJWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='g_jwt_token', to='rg.guest')),
            ],
            options={
                'db_table': 'g_jwt_token',
            },
        ),
    ]
